import { Pool } from "pg";

import { hashPassword } from "./auth.js";

const connectionString =
  process.env.DATABASE_URL ??
  "postgres://postgres:postgres@localhost:5432/recruitment";

export const demoUserId = Number(process.env.DEMO_USER_ID ?? 1);
export const demoUserEmail =
  process.env.DEMO_USER_EMAIL ?? "demo@ukcloud.local";

export const pool = new Pool({
  connectionString,
});

const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL DEFAULT 'recruiter',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
  )`,
  `ALTER TABLE users
     ADD COLUMN IF NOT EXISTS full_name TEXT`,
  `ALTER TABLE users
     ADD COLUMN IF NOT EXISTS password_hash TEXT`,
  `ALTER TABLE users
     ADD COLUMN IF NOT EXISTS auth_provider TEXT NOT NULL DEFAULT 'password'`,
  `ALTER TABLE users
     ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMPTZ`,
  `ALTER TABLE users
     ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ`,
  `ALTER TABLE users
     ADD COLUMN IF NOT EXISTS enabled_roles JSONB`,
  `ALTER TABLE users
     ADD COLUMN IF NOT EXISTS switch_pin_hash TEXT`,
  `UPDATE users
     SET enabled_roles = jsonb_build_array(role)
     WHERE enabled_roles IS NULL
        OR jsonb_typeof(enabled_roles) <> 'array'
        OR jsonb_array_length(enabled_roles) = 0`,
  `CREATE TABLE IF NOT EXISTS subscriptions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    plan TEXT NOT NULL CHECK (plan IN ('free', 'growth', 'scale', 'enterprise')),
    provider TEXT NOT NULL CHECK (provider IN ('stripe', 'paystack', 'flutterwave')),
    status TEXT NOT NULL,
    current_period_end TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id)
  )`,
  `CREATE TABLE IF NOT EXISTS deletion_requests (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    status TEXT NOT NULL CHECK (status IN ('requested', 'completed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ
  )`,
  `ALTER TABLE subscriptions
     DROP CONSTRAINT IF EXISTS subscriptions_plan_check`,
  `ALTER TABLE subscriptions
     ADD CONSTRAINT subscriptions_plan_check
     CHECK (plan IN ('free', 'growth', 'scale', 'enterprise'))`,
  `ALTER TABLE subscriptions
     DROP CONSTRAINT IF EXISTS subscriptions_provider_check`,
  `ALTER TABLE subscriptions
     ADD CONSTRAINT subscriptions_provider_check
     CHECK (provider IN ('stripe', 'paystack', 'flutterwave'))`,
  `CREATE TABLE IF NOT EXISTS profiles (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    headline TEXT NOT NULL DEFAULT '',
    location TEXT NOT NULL DEFAULT '',
    summary TEXT NOT NULL DEFAULT '',
    skills JSONB NOT NULL DEFAULT '[]'::jsonb,
    education JSONB NOT NULL DEFAULT '[]'::jsonb,
    experience_years INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `ALTER TABLE profiles
     ADD COLUMN IF NOT EXISTS education JSONB NOT NULL DEFAULT '[]'::jsonb`,
  `ALTER TABLE profiles
     ADD COLUMN IF NOT EXISTS persona_mode TEXT NOT NULL DEFAULT 'professional'`,
  `ALTER TABLE profiles
     ADD COLUMN IF NOT EXISTS sector TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE profiles
     ADD COLUMN IF NOT EXISTS hourly_rate TEXT NOT NULL DEFAULT ''`,
  `CREATE TABLE IF NOT EXISTS companies (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    website TEXT,
    industry TEXT NOT NULL DEFAULT '',
    size TEXT NOT NULL DEFAULT '',
    location TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    verification_status TEXT NOT NULL DEFAULT 'pending',
    ad_headline TEXT NOT NULL DEFAULT '',
    ad_copy TEXT NOT NULL DEFAULT '',
    created_by BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS jobs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    requirements TEXT NOT NULL DEFAULT '',
    location TEXT NOT NULL DEFAULT '',
    salary_range TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'queued',
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    created_by BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS shortlists (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recruiter_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS shortlist_items (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    shortlist_id BIGINT NOT NULL REFERENCES shortlists(id) ON DELETE CASCADE,
    candidate_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    note TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (shortlist_id, candidate_user_id)
  )`,
  `CREATE TABLE IF NOT EXISTS availability_slots (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    day_of_week INTEGER NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
    slot TEXT NOT NULL CHECK (slot IN ('morning', 'afternoon', 'evening', 'night')),
    is_available BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, day_of_week, slot)
  )`,
  `CREATE TABLE IF NOT EXISTS endorsements (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    endorser_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    target_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    points_awarded INTEGER NOT NULL DEFAULT 5,
    note TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS liquidation_requests (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    kind TEXT NOT NULL CHECK (kind IN ('discount', 'cash', 'payout')),
    points INTEGER NOT NULL DEFAULT 0,
    value_minor INTEGER NOT NULL DEFAULT 0,
    destination TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL CHECK (status IN ('pending', 'approved', 'rejected', 'paid')) DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS payout_routes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    country TEXT NOT NULL DEFAULT 'UK',
    route_type TEXT NOT NULL DEFAULT 'bank',
    bank_label TEXT NOT NULL DEFAULT '',
    account_last4 TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'ready',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS company_verifications (
    company_id BIGINT PRIMARY KEY REFERENCES companies(id) ON DELETE CASCADE,
    company_number TEXT NOT NULL DEFAULT '',
    directors JSONB NOT NULL DEFAULT '[]'::jsonb,
    companies_house_status TEXT NOT NULL DEFAULT 'pending',
    hmrc_status TEXT NOT NULL DEFAULT 'pending',
    data_residency_region TEXT NOT NULL DEFAULT 'UK',
    right_to_work_required BOOLEAN NOT NULL DEFAULT TRUE,
    retention_policy_days INTEGER NOT NULL DEFAULT 365,
    risk_notes TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS right_to_work_vault (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    document_type TEXT NOT NULL DEFAULT 'passport',
    status TEXT NOT NULL DEFAULT 'pending',
    expires_at TIMESTAMPTZ,
    retention_days INTEGER NOT NULL DEFAULT 365,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS escrow_bookings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recruiter_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    worker_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    company_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    title TEXT NOT NULL DEFAULT '',
    sector TEXT NOT NULL DEFAULT '',
    location TEXT NOT NULL DEFAULT '',
    scheduled_for TIMESTAMPTZ,
    amount_minor INTEGER NOT NULL DEFAULT 0,
    platform_fee_minor INTEGER NOT NULL DEFAULT 0,
    worker_amount_minor INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL CHECK (status IN ('held', 'released', 'disputed', 'completed', 'cancelled')) DEFAULT 'held',
    instant_book BOOLEAN NOT NULL DEFAULT FALSE,
    payout_route TEXT NOT NULL DEFAULT '',
    milestone_note TEXT NOT NULL DEFAULT '',
    dispute_reason TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS admin_cases (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    booking_id BIGINT REFERENCES escrow_bookings(id) ON DELETE CASCADE,
    company_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    type TEXT NOT NULL DEFAULT 'dispute',
    status TEXT NOT NULL CHECK (status IN ('open', 'reviewing', 'resolved', 'banned')) DEFAULT 'open',
    reason TEXT NOT NULL DEFAULT '',
    resolution_notes TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS social_posts (
    id TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE INDEX IF NOT EXISTS social_posts_user_id_idx ON social_posts(user_id)`,
];

let initialized = false;

export async function initializeDatabase() {
  if (initialized) {
    return;
  }

  for (const statement of schemaStatements) {
    await pool.query(statement);
  }

  const seedPasswordHash = hashPassword(
    process.env.DEMO_USER_PASSWORD ?? "Password123!",
  );

  await pool.query(
    `INSERT INTO users (id, email, role, enabled_roles, full_name, password_hash, email_verified_at)
     VALUES
      ($1, $2, 'recruiter', '["recruiter"]'::jsonb, 'Demo Recruiter', $3, NOW()),
      (2, 'amara.okonkwo@example.com', 'professional', '["professional"]'::jsonb, 'Amara Okonkwo', $3, NOW()),
      (3, 'james.whitfield@example.com', 'professional', '["professional"]'::jsonb, 'James Whitfield', $3, NOW()),
      (4, 'priya.nair@example.com', 'professional', '["professional"]'::jsonb, 'Priya Nair', $3, NOW()),
      (5, 'samuel.okafor@example.com', 'professional', '["professional"]'::jsonb, 'Samuel Okafor', $3, NOW()),
      (6, 'martha.adeyemi@example.com', 'professional', '["professional"]'::jsonb, 'Martha Adeyemi', $3, NOW())
     ON CONFLICT (id) DO UPDATE SET
      email = EXCLUDED.email,
      full_name = EXCLUDED.full_name,
      password_hash = EXCLUDED.password_hash,
      email_verified_at = EXCLUDED.email_verified_at`,
    [demoUserId, demoUserEmail, seedPasswordHash],
  );

  await pool.query(
    `INSERT INTO profiles (
      user_id, headline, location, summary, skills, education, experience_years, persona_mode, sector, hourly_rate
     )
     VALUES
      (2, 'Senior Product Designer', 'London, UK', 'Fintech and marketplace designer focused on trusted hiring journeys.', '["Product Design","Design Systems","Figma","User Research","Fintech"]'::jsonb, '["BSc Computer Science"]'::jsonb, 8, 'professional', 'Product Design', '£72/hr'),
      (3, 'Frontend Engineer', 'Manchester, UK', 'React and TypeScript engineer shipping recruiter tooling and growth surfaces.', '["React","TypeScript","Next.js","Node.js","GraphQL"]'::jsonb, '["BSc Software Engineering","AWS Certified Developer"]'::jsonb, 6, 'professional', 'Engineering', '£61/hr'),
      (4, 'Growth Product Manager', 'Berlin, DE', 'Cross-market product operator with African and European go-to-market experience.', '["Product Strategy","Analytics","Growth","B2B SaaS","Hiring Ops"]'::jsonb, '["MSc International Business","BSc Economics"]'::jsonb, 7, 'professional', 'Growth', '€58/hr'),
      (5, 'Warehouse Shift Supervisor', 'Birmingham, UK', 'Available for logistics, dispatch, and inventory-control shifts with immediate-start flexibility.', '["Warehouse Ops","Inventory","Forklift","Dispatch","Night Shifts"]'::jsonb, '["NVQ Level 3 Logistics"]'::jsonb, 5, 'worker', 'Logistics', '£24/hr'),
      (6, 'Care Support Worker', 'Leeds, UK', 'Experienced care worker open to day and evening support assignments across community and clinic teams.', '["Care Support","Patient Handover","Safeguarding","Medication Support","Shift Work"]'::jsonb, '["BSc Public Health","Right to Work Verified"]'::jsonb, 4, 'worker', 'Care', '£22/hr')
     ON CONFLICT (user_id) DO UPDATE SET
      headline = EXCLUDED.headline,
      location = EXCLUDED.location,
      summary = EXCLUDED.summary,
      skills = EXCLUDED.skills,
      education = EXCLUDED.education,
      experience_years = EXCLUDED.experience_years,
      persona_mode = EXCLUDED.persona_mode,
      sector = EXCLUDED.sector,
      hourly_rate = EXCLUDED.hourly_rate,
      updated_at = NOW()`,
  );

  await pool.query(
    `INSERT INTO companies (
      id, name, slug, website, industry, size, location, description, verification_status, ad_headline, ad_copy, created_by
     )
     VALUES
      (1, 'Kora Health', 'kora-health', 'https://kora.example', 'HealthTech', '51-200', 'London, UK', 'Unified talent and care operations for modern clinics.', 'verified', 'Verified hiring partner', 'Sponsor premium product and engineering roles across UK and Africa.', $1),
      (2, 'Civo Talent Cloud', 'civo-talent-cloud', 'https://civo.example', 'Cloud Infrastructure', '201-500', 'London, UK', 'UK sovereign cloud employer brand and hiring campaigns.', 'verified', 'UK sovereign cloud partner', 'Promote high-trust roles with GDPR-first candidate acquisition.', $1),
      (3, 'Paystack Growth Labs', 'paystack-growth-labs', 'https://paystack.example', 'Fintech', '501-1000', 'Lagos, NG', 'African growth and payments innovation teams hiring across regions.', 'pending', 'Expansion hiring queue', 'Launch localized ads and recruiter campaigns for African expansion.', $1)
     ON CONFLICT (id) DO UPDATE SET
      name = EXCLUDED.name,
      slug = EXCLUDED.slug,
      website = EXCLUDED.website,
      industry = EXCLUDED.industry,
      size = EXCLUDED.size,
      location = EXCLUDED.location,
      description = EXCLUDED.description,
      verification_status = EXCLUDED.verification_status,
      ad_headline = EXCLUDED.ad_headline,
      ad_copy = EXCLUDED.ad_copy,
      created_by = EXCLUDED.created_by,
      updated_at = NOW()`,
    [demoUserId],
  );

  await pool.query(
    `INSERT INTO jobs (
      id, company_id, title, description, requirements, location, salary_range, status, featured, created_by
     )
     VALUES
      (1, 1, 'Lead Product Designer', 'Own the end-to-end hiring and profile experience for healthcare teams.', 'Figma, design systems, fintech or healthtech, user research', 'Remote · UK', '£85k - £98k', 'published', TRUE, $1),
      (2, 2, 'Senior Frontend Engineer', 'Build recruiter dashboards and corporate campaign surfaces on sovereign cloud.', 'React, TypeScript, Next.js, design systems', 'London · Hybrid', '£78k - £92k', 'published', TRUE, $1),
      (3, 3, 'Growth Product Manager', 'Run localization, billing, and go-to-market experiments for African expansion.', 'B2B SaaS, analytics, growth, payments', 'Lagos · Hybrid', 'Competitive + equity', 'queued', FALSE, $1)
     ON CONFLICT (id) DO UPDATE SET
      company_id = EXCLUDED.company_id,
      title = EXCLUDED.title,
      description = EXCLUDED.description,
      requirements = EXCLUDED.requirements,
      location = EXCLUDED.location,
      salary_range = EXCLUDED.salary_range,
      status = EXCLUDED.status,
      featured = EXCLUDED.featured,
      created_by = EXCLUDED.created_by,
      updated_at = NOW()`,
    [demoUserId],
  );

  await pool.query(
    `INSERT INTO shortlists (id, recruiter_user_id, name)
     VALUES
      (1, $1, 'UK Product Talent'),
      (2, $1, 'Africa Expansion Leaders')
     ON CONFLICT (id) DO UPDATE SET
      recruiter_user_id = EXCLUDED.recruiter_user_id,
      name = EXCLUDED.name,
      updated_at = NOW()`,
    [demoUserId],
  );

  await pool.query(
    `INSERT INTO shortlist_items (shortlist_id, candidate_user_id, note)
     VALUES
      (1, 2, 'Strong fintech systems background'),
      (1, 3, 'Fits frontend platform hiring'),
      (2, 4, 'Relevant for African SaaS expansion')
     ON CONFLICT (shortlist_id, candidate_user_id) DO UPDATE SET
      note = EXCLUDED.note`,
  );

  await pool.query(
    `INSERT INTO availability_slots (user_id, day_of_week, slot, is_available)
     VALUES
      (2, 0, 'morning', TRUE),
      (2, 1, 'afternoon', TRUE),
      (2, 3, 'evening', TRUE),
      (5, 0, 'night', TRUE),
      (5, 1, 'night', TRUE),
      (5, 4, 'morning', TRUE),
      (6, 0, 'morning', TRUE),
      (6, 2, 'afternoon', TRUE),
      (6, 3, 'evening', TRUE)
     ON CONFLICT (user_id, day_of_week, slot) DO UPDATE SET
      is_available = EXCLUDED.is_available,
      updated_at = NOW()`,
  );

  await pool.query(
    `INSERT INTO endorsements (id, endorser_user_id, target_user_id, points_awarded, note)
     VALUES
      (1, 3, 2, 8, 'Trusted design systems partner for regulated products.'),
      (2, 1, 5, 6, 'Strong instant-start logistics candidate with dependable shift coverage.'),
      (3, 4, 6, 7, 'Reliable care worker with excellent handover notes and punctuality.')
     ON CONFLICT (id) DO UPDATE SET
      endorser_user_id = EXCLUDED.endorser_user_id,
      target_user_id = EXCLUDED.target_user_id,
      points_awarded = EXCLUDED.points_awarded,
      note = EXCLUDED.note`,
  );

  await pool.query(
    `INSERT INTO liquidation_requests (id, user_id, kind, points, value_minor, destination, status)
     VALUES
      (1, 5, 'discount', 12, 1200, 'Growth plan credit', 'approved'),
      (2, 6, 'cash', 10, 1000, 'UK debit payout', 'pending')
     ON CONFLICT (id) DO UPDATE SET
      user_id = EXCLUDED.user_id,
      kind = EXCLUDED.kind,
      points = EXCLUDED.points,
      value_minor = EXCLUDED.value_minor,
      destination = EXCLUDED.destination,
      status = EXCLUDED.status,
      updated_at = NOW()`,
  );

  await pool.query(
    `INSERT INTO payout_routes (id, user_id, country, route_type, bank_label, account_last4, status)
     VALUES
      (1, 5, 'UK', 'bank', 'Barclays Business', '4821', 'ready'),
      (2, 6, 'UK', 'bank', 'Monzo Personal', '1930', 'ready')
     ON CONFLICT (id) DO UPDATE SET
      user_id = EXCLUDED.user_id,
      country = EXCLUDED.country,
      route_type = EXCLUDED.route_type,
      bank_label = EXCLUDED.bank_label,
      account_last4 = EXCLUDED.account_last4,
      status = EXCLUDED.status,
      updated_at = NOW()`,
  );

  await pool.query(
    `INSERT INTO company_verifications (
      company_id, company_number, directors, companies_house_status, hmrc_status, data_residency_region, right_to_work_required, retention_policy_days, risk_notes
     )
     VALUES
      (1, '11223344', '["A. Hassan","J. Madu"]'::jsonb, 'verified', 'verified', 'UK', TRUE, 365, 'Health staffing only; keep right-to-work vault current.'),
      (2, '22334455', '["L. Patel","R. Clarke"]'::jsonb, 'verified', 'verified', 'UK', TRUE, 365, 'Cloud employer with UK residency routing requirement.'),
      (3, '33445566', '["T. Adeyemi"]'::jsonb, 'review', 'pending', 'UK', TRUE, 365, 'Awaiting VAT/PAYE evidence for expanded campaigns.')
     ON CONFLICT (company_id) DO UPDATE SET
      company_number = EXCLUDED.company_number,
      directors = EXCLUDED.directors,
      companies_house_status = EXCLUDED.companies_house_status,
      hmrc_status = EXCLUDED.hmrc_status,
      data_residency_region = EXCLUDED.data_residency_region,
      right_to_work_required = EXCLUDED.right_to_work_required,
      retention_policy_days = EXCLUDED.retention_policy_days,
      risk_notes = EXCLUDED.risk_notes,
      updated_at = NOW()`,
  );

  await pool.query(
    `INSERT INTO right_to_work_vault (id, user_id, document_type, status, expires_at, retention_days)
     VALUES
      (1, 5, 'passport', 'verified', NOW() + INTERVAL '365 days', 365),
      (2, 6, 'residence-permit', 'verified', NOW() + INTERVAL '240 days', 365)
     ON CONFLICT (id) DO UPDATE SET
      user_id = EXCLUDED.user_id,
      document_type = EXCLUDED.document_type,
      status = EXCLUDED.status,
      expires_at = EXCLUDED.expires_at,
      retention_days = EXCLUDED.retention_days`,
  );

  await pool.query(
    `INSERT INTO escrow_bookings (
      id, recruiter_user_id, worker_user_id, company_id, title, sector, location, scheduled_for, amount_minor, platform_fee_minor, worker_amount_minor, status, instant_book, payout_route, milestone_note, dispute_reason
     )
     VALUES
      (1, $1, 5, 1, 'Weekend warehouse dispatch cover', 'Logistics', 'Birmingham, UK', NOW() + INTERVAL '2 days', 32000, 3840, 28160, 'held', TRUE, 'Barclays Business ••••4821', 'Funds held until shift sign-off.', ''),
      (2, $1, 6, 1, 'Evening care support block', 'Care', 'Leeds, UK', NOW() + INTERVAL '1 day', 28000, 3360, 24640, 'disputed', TRUE, 'Monzo Personal ••••1930', 'Release on care lead completion check.', 'Timesheet mismatch under review.')
     ON CONFLICT (id) DO UPDATE SET
      recruiter_user_id = EXCLUDED.recruiter_user_id,
      worker_user_id = EXCLUDED.worker_user_id,
      company_id = EXCLUDED.company_id,
      title = EXCLUDED.title,
      sector = EXCLUDED.sector,
      location = EXCLUDED.location,
      scheduled_for = EXCLUDED.scheduled_for,
      amount_minor = EXCLUDED.amount_minor,
      platform_fee_minor = EXCLUDED.platform_fee_minor,
      worker_amount_minor = EXCLUDED.worker_amount_minor,
      status = EXCLUDED.status,
      instant_book = EXCLUDED.instant_book,
      payout_route = EXCLUDED.payout_route,
      milestone_note = EXCLUDED.milestone_note,
      dispute_reason = EXCLUDED.dispute_reason,
      updated_at = NOW()`,
    [demoUserId],
  );

  await pool.query(
    `INSERT INTO admin_cases (id, booking_id, company_id, type, status, reason, resolution_notes)
     VALUES
      (1, 2, 1, 'dispute', 'reviewing', 'Worker and manager submitted conflicting completion notes.', 'Reviewing shift logs and payout hold.')
     ON CONFLICT (id) DO UPDATE SET
      booking_id = EXCLUDED.booking_id,
      company_id = EXCLUDED.company_id,
      type = EXCLUDED.type,
      status = EXCLUDED.status,
      reason = EXCLUDED.reason,
      resolution_notes = EXCLUDED.resolution_notes,
      updated_at = NOW()`,
  );

  await pool.query(
    `SELECT setval('users_id_seq', COALESCE((SELECT MAX(id) FROM users), 1), true)`,
  );
  await pool.query(
    `SELECT setval('companies_id_seq', COALESCE((SELECT MAX(id) FROM companies), 1), true)`,
  );
  await pool.query(
    `SELECT setval('jobs_id_seq', COALESCE((SELECT MAX(id) FROM jobs), 1), true)`,
  );
  await pool.query(
    `SELECT setval('shortlists_id_seq', COALESCE((SELECT MAX(id) FROM shortlists), 1), true)`,
  );
  await pool.query(
    `SELECT setval('endorsements_id_seq', COALESCE((SELECT MAX(id) FROM endorsements), 1), true)`,
  );
  await pool.query(
    `SELECT setval('liquidation_requests_id_seq', COALESCE((SELECT MAX(id) FROM liquidation_requests), 1), true)`,
  );
  await pool.query(
    `SELECT setval('payout_routes_id_seq', COALESCE((SELECT MAX(id) FROM payout_routes), 1), true)`,
  );
  await pool.query(
    `SELECT setval('right_to_work_vault_id_seq', COALESCE((SELECT MAX(id) FROM right_to_work_vault), 1), true)`,
  );
  await pool.query(
    `SELECT setval('escrow_bookings_id_seq', COALESCE((SELECT MAX(id) FROM escrow_bookings), 1), true)`,
  );
  await pool.query(
    `SELECT setval('admin_cases_id_seq', COALESCE((SELECT MAX(id) FROM admin_cases), 1), true)`,
  );

  initialized = true;
}

export async function getUserById(userId: number) {
  const result = await pool.query(
    `SELECT id, email, role, enabled_roles, full_name, password_hash, switch_pin_hash, auth_provider, email_verified_at, last_login_at, created_at, deleted_at
     FROM users
     WHERE id = $1`,
    [userId],
  );

  return result.rows[0] ?? null;
}
