import { Pool } from "pg";

const connectionString =
  process.env.DATABASE_URL ??
  "postgres://postgres:postgres@localhost:5432/recruitment";

export const demoUserId = Number(process.env.DEMO_USER_ID ?? 1);
export const demoUserEmail =
  process.env.DEMO_USER_EMAIL ?? "demo@ukcloud.local";

export const pool = new Pool({
  connectionString,
});

const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL DEFAULT 'recruiter',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
  )`,
  `CREATE TABLE IF NOT EXISTS subscriptions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    plan TEXT NOT NULL CHECK (plan IN ('free', 'growth', 'scale')),
    provider TEXT NOT NULL CHECK (provider IN ('stripe', 'paystack')),
    status TEXT NOT NULL,
    current_period_end TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id)
  )`,
  `CREATE TABLE IF NOT EXISTS deletion_requests (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    status TEXT NOT NULL CHECK (status IN ('requested', 'completed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ
  )`,
];

let initialized = false;

export async function initializeDatabase() {
  if (initialized) {
    return;
  }

  for (const statement of schemaStatements) {
    await pool.query(statement);
  }

  await pool.query(
    `INSERT INTO users (id, email, role)
     VALUES ($1, $2, 'recruiter')
     ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email`,
    [demoUserId, demoUserEmail],
  );

  initialized = true;
}

export async function getUserById(userId: number) {
  const result = await pool.query(
    `SELECT id, email, role, created_at, deleted_at
     FROM users
     WHERE id = $1`,
    [userId],
  );

  return result.rows[0] ?? null;
}
